/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

module.exports = function(config) {
  return {
    options: {
      build: ['build']
    },
    dev: {
      options: {
        build: ['build:dev'],
        dev: true
      }
    },
    prod: {
      options: {
        prod: true
      }
    }
  };
}