/* jshint node: true */
'use strict';

/*
This file was generated by generator-ffwd,
you probably should not modify it
*/

var exampleFeature = require('./server');

var app = require('ffwd-net/server')({
  features: {
    'example-feature': exampleFeature
  }
});

module.exports = app;

console.info('papi papo');
var s = 0;
setInterval(function() {
  s++;
  console.info('started '+ s +' sec ago on port: '+ process.env.NODE_PORT);
}, 1000);

if (process.env.NODE_PORT) {
  app.set('port', process.env.NODE_PORT);
  require('http').createServer(app).listen(app.get('port'), function(){
    console.log('Express server listening on port ' + app.get('port'))
  });
}